#H2
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test3;
    username: sa
    password:
    driver-class-name: org.h2.Driver

#JPA
  jpa:
    hibernate:
      ddl-auto: none


logging:
  level:
    org.springframework.security: debug

